# Start with the Docker in Docker image
FROM docker:dind

# Install bash, Node.js, jq, and Perl
RUN apk add --update nodejs npm bash jq perl

# Install Gala Chain CLI globally
RUN npm install -g @gala-chain/cli

# Install Nodemon globally
RUN npm install -g nodemon

# Start the Docker daemon as a background process and tail its log file
CMD dockerd > /var/log/dockerd.log 2>&1 & tail -f /var/log/dockerd.log
