name: SDK Version bump

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch (main or main-v*)'
        required: true
        default: 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    name: Bump SDK Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch }}
          token: ${{ github.token }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install tools
        run: npm i -g semver

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set a new version
        run: |
          VERSION="$(semver "$(jq -r '.version' package.json)" -i patch)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create a new branch
        run: |
          BRANCH_NAME="bump-version-to-$VERSION"
          git checkout -b "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Bump version and commit changes
        run: |
          ./unifyVersions.js "$VERSION"
          npm i
          git add .
          git commit -m "Bump version to $VERSION"
          git push --set-upstream origin "$BRANCH_NAME"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --title "Bump Version to $VERSION" \
            --body "Bump Version to $VERSION" \
            --label "bump-version-pr" \
            --head "$BRANCH_NAME" \
            --base "${{ inputs.target_branch }}"
