name: Publish CLI Docker image
on:
  push:
    paths:
    - 'chain-cli/docker/Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: galachain/sdk

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Make the repository name lowercase
      id: lower-repo
      shell: pwsh
      run: |
        "::set-output name=repository::$($env:GITHUB_REPOSITORY.ToLowerInvariant())"
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./chain-cli/docker
        push: true
        tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest